### ISSUE TITLE
MTG API Comparison

### ISSUE THREAD

**Issue by s32989** [cjn98/deckbop#10]
https://scryfall.com/docs/api
https://docs.magicthegathering.io/

**Comment by s32989** [comment]
using the scryfall API:

we can use this page to form query strings:

https://scryfall.com/docs/syntax

here are some examples that might be helpful (based off of the deck editor mockup)

searching for a card:
https://api.scryfall.com/cards/search/?q=[CARDNAME]

searching for a set
https://api.scryfall.com/cards/search/?q=s%3A[SET]

searching for a color:
https://api.scryfall.com/cards/search/?q=c%3A[COLOR]

searching for a card type:
https://api.scryfall.com/cards/search/?q=type%3A[CARDTYPE]

these can be chained together with "+"

for example:  a search for red enchantments:
https://api.scryfall.com/cards/search/?q=type%3Aenchantment+c%3Ared

**Comment by cobbettn** [comment]
Add this to a page in the wiki and then this can be closed 🐱‍🏍
