### ISSUE TITLE
Story - create db population script

### ISSUE THREAD

**Issue by cobbettn** [cjn98/deckbop#2]
write script that creates schema and tables in db

https://github.com/cjn98/deckbop/wiki/DB-tables

**Comment by s32989** [comment]
BEGIN TRANSACTION;

create database deckbop;

CREATE TABLE Users
(
        user_id serial,
        username varchar(64) NOT NULL,
        pw varchar(64) NOT NULL,
        email varchar(64),

        constraint pk_Users primary key(user_id)
        
);

CREATE TABLE Decks
(
        deck_id serial,
        user_id int,
        decklist_id int,
	deck_name varchar(64),
    
        constraint pk_Decks primary key(deck_id),
        constraint fk_user_deck foreign key(user_id) references Users(user_id)
      
);

CREATE TABLE Decklist
(
        deck_id int,
        card_id int,
	card_quantity int,
        
        constraint fk_decklist_deck foreign key (deck_id) references Decks(deck_id)
        
);

COMMIT TRANSACTION;
