### ISSUE TITLE
Spike - mock ups

### ISSUE THREAD

**Issue by cobbettn** [cjn98/deckbop#4]
make some mockups for mvp

https://github.com/cjn98/deckbop/wiki/MVP

figma?

**Comment by ccrisson** [comment]
[DeckBopMockup_ViewDecks.pdf](https://github.com/cjn98/deckbop/files/5812220/DeckBopMockup_ViewDecks.pdf)
[DeckBopMockup_Login.pdf](https://github.com/cjn98/deckbop/files/5812221/DeckBopMockup_Login.pdf)
[DeckBopMockup_DeckEditor.pdf](https://github.com/cjn98/deckbop/files/5812222/DeckBopMockup_DeckEditor.pdf)
Color Scemes
https://visme.co/blog/wp-content/uploads/2016/09/website19-1024x512.jpg
https://visme.co/blog/wp-content/uploads/2016/09/website42-1024x512.jpg
**https://visme.co/blog/wp-content/uploads/2016/09/website17-1024x512.jpg**
https://visme.co/blog/wp-content/uploads/2016/09/website14-1024x512.jpg
https://visme.co/blog/wp-content/uploads/2016/09/website9-1024x512.jpg
https://visme.co/blog/wp-content/uploads/2016/09/website4-1024x512.jpg
https://visme.co/blog/website-color-schemes/
