### ISSUE TITLE
deck editor layout

### ISSUE THREAD

**Issue by cobbettn** [cjn98/deckbop#69]
**Describe the solution you'd like**
reseearch possible deck editor layout solutions

css transform vs custom elments for dispalying iamges?

**Additional context**

**Comment by ccrisson** [comment]
This is able to work just using flex. 
.card-container{
  display: inline-flex;
  flex-direction: column;
}
.card {
  position: relative;
  overflow:hidden;
  width: 200px;
}
.card:not(:last-child) {
  margin-bottom: -95%;
}

https://codepen.io/ccrisson/pen/qBqBPve
