### ISSUE TITLE
add error and success messages to the register page

### ISSUE THREAD

**Issue by cobbettn** [cjn98/deckbop#72]
**Describe the solution you'd like**

returns:

- 201 on create
- 400 on bad creds

use the status codes to dispaly success/error messages

**Additional context**

**Comment by ccrisson** [comment]
I wired it up to the backend in <a href="https://github.com/cjn98/deckbop/issues/74">this issue</a>. It still needs to be implimented better in tandem with the backend as it currently does not return a useful response.
