### ISSUE TITLE
Epic - Deck editor

### ISSUE THREAD

**Issue by ccrisson** [cjn98/deckbop#76]
The Deck Editor should allow the user to search for a card by name and view the search results.
When a user clicks on a card from the search results the card should be added to the deck view.
When a user clicks on a card from the deck view it should remove it from the deck.
A user should be able to name and save the deck to the db on the backend.

**Comment by cobbettn** [comment]
@ccrisson looks like this is all done except for the deck save part, is that coming along okay?
